language: go

go:
  - 1.12.x

go_import_path: github.com/jurocknsail/gojira

env:
  global:
    - ARTIFACT_NAME=gojira.exe

before_install:

script:
- GO111MODULE=on GOOS=windows GOARCH=amd64 go build -o bin/$ARTIFACT_NAME

deploy:
- provider: releases
  api_key: $GITHUB_API_KEY
  file: bin/$ARTIFACT_NAME
  skip_cleanup: true # Important, otherwise the build output would be purged.
  on:
    tags: true # The deployment happens only if the commit has a tag.